version: "3.8"
services:
  base:
    container_name: servidorbase
    image: ub-base
    build:
      context: ${DIR_DFILES}/ubuntu/base
      dockerfile: ./Dockerfile
    env_file:
      - ./.env
    volumes:
      - ".:/var/logs"
    networks:
      netansible:
          ipv4_address: 172.120.10.2
volumes:
  vlogs:
networks:
  netansible:
      ipam:
          driver: default
          config:
              - subnet: 172.120.10.0/24
